# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import hstool.models
import hstool.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_auto_20150615_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.BooleanField(default=True)),
                ('author_id', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Country')),
                ('geographical_scope', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.GeographicalScope')),
            ],
            options={
                'permissions': (('create', 'Create an assessment'), ('config', 'Can change configuration')),
            },
        ),
        migrations.CreateModel(
            name='DriverOfChangeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='GenericElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.BooleanField(default=True)),
                ('author_id', models.CharField(max_length=64)),
                ('short_name', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=512)),
                ('url', models.CharField(blank=True, max_length=256, null=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='IndicatorFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=hstool.utils.path_and_rename_indicators)),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft', models.BooleanField(default=True)),
                ('relationship_type', models.IntegerField(blank=True, choices=[(1, b'Cause-effect relationship'), (2, b'Neutral relationship')], null=True)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='hstool.Assessment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SteepCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TimeHorizon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('author_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DriverOfChange',
            fields=[
                ('genericelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hstool.GenericElement')),
                ('trend_type', models.IntegerField(choices=[(1, b'Trend'), (2, b'Megatrend')], default=1)),
                ('uncertainty_type', models.IntegerField(choices=[(1, b'Rationale'), (2, b'Data'), (3, b'Methodology (related to the model)')], default=1)),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('hstool.genericelement', models.Model),
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('genericelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hstool.GenericElement')),
                ('file', hstool.models.ContentTypeRestrictedFileField(upload_to=hstool.utils.path_and_rename_figures)),
            ],
            options={
                'abstract': False,
            },
            bases=('hstool.genericelement', models.Model),
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('genericelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hstool.GenericElement')),
                ('description', models.TextField()),
                ('impact_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impact_type', to='hstool.ImpactType')),
            ],
            options={
                'abstract': False,
            },
            bases=('hstool.genericelement', models.Model),
        ),
        migrations.CreateModel(
            name='Implication',
            fields=[
                ('genericelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hstool.GenericElement')),
                ('policy_area', models.CharField(blank=True, choices=[(b'mock_policy', b'Mock policy')], default=0, max_length=64, null=True)),
                ('description', models.TextField(max_length=2048)),
            ],
            options={
                'abstract': False,
            },
            bases=('hstool.genericelement', models.Model),
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('genericelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hstool.GenericElement')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('assessment', models.TextField(blank=True, null=True)),
                ('assessment_author', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('hstool.genericelement', models.Model),
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('genericelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='hstool.GenericElement')),
                ('title_original', models.CharField(blank=True, max_length=512, null=True)),
                ('published_year', models.CharField(max_length=4)),
                ('author', models.CharField(max_length=512)),
                ('file', models.FileField(blank=True, null=True, upload_to=hstool.utils.path_and_rename_sources)),
                ('summary', models.TextField(blank=True, max_length=2048, null=True)),
            ],
            bases=('hstool.genericelement',),
        ),
        migrations.AddField(
            model_name='relation',
            name='destination',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='dest_relations', to='hstool.GenericElement'),
        ),
        migrations.AddField(
            model_name='genericelement',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.Country'),
        ),
        migrations.AddField(
            model_name='genericelement',
            name='geographical_scope',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.GeographicalScope'),
        ),
        migrations.AddField(
            model_name='relation',
            name='figures',
            field=models.ManyToManyField(blank=True, to='hstool.Figure'),
        ),
        migrations.AddField(
            model_name='relation',
            name='indicators',
            field=models.ManyToManyField(blank=True, to='hstool.Indicator'),
        ),
        migrations.AddField(
            model_name='relation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_relations', to='hstool.DriverOfChange'),
        ),
        migrations.AddField(
            model_name='indicatorfiles',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hstool.Indicator'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='sources',
            field=models.ManyToManyField(blank=True, to='hstool.Source'),
        ),
        migrations.AddField(
            model_name='indicator',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.EnvironmentalTheme'),
        ),
        migrations.AddField(
            model_name='implication',
            name='sources',
            field=models.ManyToManyField(blank=True, to='hstool.Source'),
        ),
        migrations.AddField(
            model_name='impact',
            name='sources',
            field=models.ManyToManyField(blank=True, to='hstool.Source'),
        ),
        migrations.AddField(
            model_name='impact',
            name='steep_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='impact_category', to='hstool.SteepCategory'),
        ),
        migrations.AddField(
            model_name='figure',
            name='sources',
            field=models.ManyToManyField(blank=True, to='hstool.Source'),
        ),
        migrations.AddField(
            model_name='figure',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.EnvironmentalTheme'),
        ),
        migrations.AddField(
            model_name='driverofchange',
            name='figures',
            field=models.ManyToManyField(blank=True, to='hstool.Figure'),
        ),
        migrations.AddField(
            model_name='driverofchange',
            name='impacts',
            field=models.ManyToManyField(blank=True, to='hstool.Impact'),
        ),
        migrations.AddField(
            model_name='driverofchange',
            name='implications',
            field=models.ManyToManyField(blank=True, to='hstool.Implication'),
        ),
        migrations.AddField(
            model_name='driverofchange',
            name='indicators',
            field=models.ManyToManyField(blank=True, to='hstool.Indicator'),
        ),
        migrations.AddField(
            model_name='driverofchange',
            name='sources',
            field=models.ManyToManyField(blank=True, to='hstool.Source'),
        ),
        migrations.AddField(
            model_name='driverofchange',
            name='steep_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_category', to='hstool.SteepCategory'),
        ),
        migrations.AddField(
            model_name='driverofchange',
            name='time_horizon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_time', to='hstool.TimeHorizon'),
        ),
        migrations.AddField(
            model_name='driverofchange',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doc_type', to='hstool.DriverOfChangeType'),
        ),
    ]
