language: python
python:
  - "2.7"
install:
  - pip install -r requirements-dev.txt --use-mirrors
  - cp hstool/local_settings.py.example hstool/local_settings.py
script:  ./manage.py test 
after_success: coveralls
notifications:
  email:
    recipients:
      - purepython@eaudeweb.ro
