language: python
python:
  - "2.7"
install:
  - pip install -r requirements-dev.txt
  - cp hstool/test_settings.py.example hstool/test_settings.py
  - ./manage.py collectstatic --noinput
script:  ./manage.py test
after_success: coveralls
notifications:
  email:
    recipients:
      - purepython@eaudeweb.ro
